name: If Demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if the branch is main
        if: ${{ github.ref_name == 'develop' }}
        run: echo "Running from main branch"
