name: If Demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step with if
        if: ${{ github.ref == 'refs/headss/main' }}
        run: echo "Running from main branch"
      - name: Run this step
        run: echo "No if statememnt"
